---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: rancher/dapper:v0.6.0
    environment:
      OAUTH_TOKEN:
        from_secret: github_token
    privileged: true
    commands:
      - dapper ci
      - bin/authtool --version
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - push
        - pull_request
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  event:
    exclude:
      - tag

node:
  instance: agent-amd64

---

kind: pipeline
type: docker
name: package

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: rancher/dapper:v0.6.0
    environment:
      OAUTH_TOKEN:
        from_secret: github_token
    privileged: true
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: cnrancher/authtool
      tag: "${DRONE_TAG}"
      username:
        from_secret: docker_username
  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      files:
        - "bin/authtool"

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
trigger:
  event:
    include:
      - tag

node:
  instance: agent-amd64