# Add a comment to force a change.

name: Webhook CI

on:
  push:
    branches:
      - master
      - release/v*
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
  workflow_dispatch:

permissions:
  contents: read

env:
  OAUTH_TOKEN: ${{ secrets.RD_ONLY_GH_TOKEN }}

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name : Checkout repository
        # https://github.com/actions/checkout/releases/tag/v4.1.1
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        # https://github.com/actions/setup-go/releases/tag/v5.0.0
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'

      - name: ci
        run: make ci
