name: release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: write

env:
  OAUTH_TOKEN: ${{ secrets.RD_ONLY_GH_TOKEN }}

jobs:
  release:
    name: build and release
    runs-on: ubuntu-latest
    steps:

      - name : Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        # https://github.com/actions/checkout/releases/tag/v4.1.1

      - name: Setup Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        # https://github.com/actions/setup-go/releases/tag/v5.0.0
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: |
          ./scripts/build
          mkdir -p dist/artifacts
          cp bin/authtool dist/artifacts/authtool

      - name: Generate checksum files
        run: |
          ls -lR dist
          cd dist/artifacts
          sha256sum authtool > sha256sum.txt

#      - name: Upload artifacts
#        # https://github.com/actions/upload-artifact/commit/65462800fd760344b1a7b4382951275a0abb4808
#        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
#        with:
#          name: authtool-artifacts
#          path: |
#            dist/artifacts/authtool
#            dist/artifacts/sha256sum.txt
      - name: Get the version
        run: |
          source ./scripts/version
          echo "TAG=$(echo $TAG | sed 's/-amd64$//')" >> $GITHUB_ENV

      - name: Upload the files
        run: |
          ls -lR dist
          cd dist/artifacts
          gh --repo "${{ github.repository }}" release create ${{ github.ref_name }} --prerelease --verify-tag --generate-notes authtool sha256sum.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
